package com.example.powerai.engine.ai

data class SmartAbRunRecord(
    val sessionId: String,
    val status: String,
    val query: String,
    val answerMode: String,
    val backendMode: String,
    val threadMode: String,
    val batchMode: String,
    val batchThreadMode: String,
    val startedAtEpochMs: Long,
    val finishedAtEpochMs: Long,
    val retrievalMs: Long? = null,
    val promptBuildMs: Long? = null,
    val firstTokenLatencyMs: Long? = null,
    val answerStartLatencyMs: Long? = null,
    val decodeCharsPerSecond: Double? = null,
    val streamedChunkCount: Int? = null,
    val rawOutputLength: Int? = null,
    val finalAnswerLength: Int? = null,
    val evidenceCount: Int = 0,
    val promptChars: Int = 0,
    val errorMessage: String? = null,
    val prefixReuseEnabled: Boolean = false,
    val prefixReuseHit: Boolean = false,
    val stateSnapshotReuseEnabled: Boolean = false,
    val stateSnapshotReuseHit: Boolean = false,
    val stateSnapshotBytes: Int = 0,
    val cachePromptEnabled: Boolean = false,
    val cacheReuseMinTokens: Int = 0,
    val benchmarkKind: String? = null,
    val benchmarkGroupId: String? = null,
    val benchmarkOrder: Int? = null
)
